name: Build Docker Image

on:
  # to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # push:
  #   branches:
  #     - main

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build :latest
        if: success()
        run: docker build -t weaigc/bingo:latest .

      - name: Push to docker hub :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push weaigc/bingo:latest
